// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn4et9TLnJZvjzR2uXFqwvtH_8DNLOOgA',
    appId: '1:759806337500:web:d09b6b17bf0cca066eef19',
    messagingSenderId: '759806337500',
    projectId: 'privatenotes-fuletter',
    authDomain: 'privatenotes-fuletter.firebaseapp.com',
    storageBucket: 'privatenotes-fuletter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDox7NYMxPhHN24-AZRvot2CGpv6FV-A5Q',
    appId: '1:759806337500:android:f8a2f9e0bccdff2a6eef19',
    messagingSenderId: '759806337500',
    projectId: 'privatenotes-fuletter',
    storageBucket: 'privatenotes-fuletter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDosOCL6QN6Rk4dY5t9AElVI6m8v9t1Vw',
    appId: '1:759806337500:ios:bb8e2a1ae6d9778c6eef19',
    messagingSenderId: '759806337500',
    projectId: 'privatenotes-fuletter',
    storageBucket: 'privatenotes-fuletter.appspot.com',
    iosClientId: '759806337500-jacsqv0tof8ekvf6sf27hvhe5iq2ij8g.apps.googleusercontent.com',
    iosBundleId: 'com.kelpdashistock.privatenotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDosOCL6QN6Rk4dY5t9AElVI6m8v9t1Vw',
    appId: '1:759806337500:ios:bb8e2a1ae6d9778c6eef19',
    messagingSenderId: '759806337500',
    projectId: 'privatenotes-fuletter',
    storageBucket: 'privatenotes-fuletter.appspot.com',
    iosClientId: '759806337500-jacsqv0tof8ekvf6sf27hvhe5iq2ij8g.apps.googleusercontent.com',
    iosBundleId: 'com.kelpdashistock.privatenotes',
  );
}
